/*
 * generated by Xtext 2.11.0.RC2
 */
package com.realitylattice.ide

import com.google.inject.Guice
import com.realitylattice.RLatRuntimeModule
import com.realitylattice.RLatStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class RLatIdeSetup extends RLatStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new RLatRuntimeModule, new RLatIdeModule))
	}
	
}
