/*
 * generated by Xtext
 */
package com.realitylattice.ui.contentassist

import com.realitylattice.ui.contentassist.AbstractRLatProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class RLatProposalProvider extends AbstractRLatProposalProvider {
}
