/*
 * generated by Xtext 2.11.0.RC2
 */
package com.realitylattice.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class RLatUiModule extends AbstractRLatUiModule {
}
