/*
 * generated by Xtext 2.11.0.RC2
 */
package com.realitylattice


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RLatStandaloneSetup extends RLatStandaloneSetupGenerated {

	def static void doSetup() {
		new RLatStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
